### PR TITLE
chore: Bump AMF and other dependencies

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
Bumps the AMF and other dependencies to remove indirect dependency on old `fsm` project. Tested with a successful simulation.

### CODE REVIEW

**Comment by gab-arrobo** [comment]
@ghislainbourgeois, what about making `gnbsim` independent from the `amf`? In other words, make one image independent from another one? is it doable? As far as I remember, I think there are a couple (a few) structs from the `amf` that are used in the `gnbsim`, can these structs be move to the `util` repo or other auxiliary repo such that `gnbsim` does not have to depend on the `amf`?

**Comment by ghislainbourgeois** [comment]
> @ghislainbourgeois, what about making `gnbsim` independent from the `amf`? In other words, make one image independent from another one? is it doable? As far as I remember, I think there are a couple (a few) structs from the `amf` that are used in the `gnbsim`, can these structs be move to the `util` repo or other auxiliary repo such that `gnbsim` does not have to depend on the `amf`?

Those structs are used only by those 2 services, so I am not sure it makes sense to move them to the `util` project. I do not have a strong opinion either way, particularly because `gnbsim` is only used for testing. In the end, only the needed structs will be compiled in the final binary.

We can go the route of moving the structs to the util project, but this will be more involved, requiring 3 PRs in 3 different projects. Let me know what you prefer.

**Comment by gab-arrobo** [comment]
> > @ghislainbourgeois, what about making `gnbsim` independent from the `amf`? In other words, make one image independent from another one? is it doable? As far as I remember, I think there are a couple (a few) structs from the `amf` that are used in the `gnbsim`, can these structs be move to the `util` repo or other auxiliary repo such that `gnbsim` does not have to depend on the `amf`?
> 
> Those structs are used only by those 2 services, so I am not sure it makes sense to move them to the `util` project. I do not have a strong opinion either way, particularly because `gnbsim` is only used for testing. In the end, only the needed structs will be compiled in the final binary.
> 
> We can go the route of moving the structs to the util project, but this will be more involved, requiring 3 PRs in 3 different projects. Let me know what you prefer.

It is a good point that only the `gNBSim` uses the `amf`. Then we can leave this PR as is. Thanks!

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes with OnRamp)

**Pull request merged**
