### PR TITLE
Support statistics at proc level & trans level

### PR DESCRIPTION
**Pull request by thakurajayL**
When program stops it will give summary of following procedures. Also the breakup of the transactions is provided wherever applicable. Mostly in case of Registration.
    - UE Registration,
    - PDU Session Est
    - UE Deregistration
    - Service Request
    - AN Release

### CODE REVIEW

**Comment by gab-arrobo** [comment]
This is the error I get when using this patch:

```
$ make 5g-test
...
...
2024-01-17T23:21:30Z [INFO][GNBSIM][SimUe][imsi-208930100007500] Handling event: SERVICE-ACCEPT-EVENT
2024/01/17 23:21:30 *******Received Event : SVC_ACCEPT_IN:  &{imsi-208930100007500 35 220 0001-01-01 00:00:00 +0000 UTC}
2024/01/17 23:21:30 No transaction found for Id: 220
cmac value: 0x9f25f5d3
2024-01-17T23:21:30Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Wrote 24 bytes
2024-01-17T23:21:30Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Message Id ****************  0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xadb92b]

goroutine 19 [running]:
github.com/omec-project/gnbsim/stats.readStats()
        /go/src/gnbsim/stats/stats.go:277 +0x1a4b
created by github.com/omec-project/gnbsim/stats.init.0 in goroutine 1
        /go/src/gnbsim/stats/stats.go:125 +0x54
command terminated with exit code 2
```

**Comment by thakurajayL** [comment]
Given the merge conflict. I am not sure if you used old code. Let me fix the merge conflict and then see.

**Comment by gab-arrobo** [comment]
> Given the merge conflict. I am not sure if you used old code. Let me fix the merge conflict and then see.

No, the issue with the test was before the "conflict". The conflict showed up because PR #116 was merged and `gnodeb/worker/gnbamfworker/handler.go` was modified in that PR.

**Comment by gab-arrobo** [comment]
you need to run `$ golangci-lint run -v --config ./.golangci.yml` in your system to make sure that everything with your changes is ok

**Review by gab-arrobo — CHANGES_REQUESTED** [review]

**Comment by gab-arrobo** [comment]
@thakurajayL, please address conflicts

**Comment by gab-arrobo** [comment]
@thakurajayL, please rebase your PR and resolve conflicts.

**Comment by gab-arrobo** [comment]
@patriciareinoso, any suggestion on how to fix the lint issue in this PR? Thanks!
 ```bash
$ golangci-lint run -v --config ./.golangci.yml
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 11 linters: [asciicheck dogsled goconst godox gofmt gofumpt govet ineffassign misspell staticcheck unused]
INFO [loader] Go packages loading at mode 575 (types_sizes|compiled_files|exports_file|files|imports|deps|name) took 834.21036ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 15.41072ms
INFO [linters_context/goanalysis] analyzers took 0s with no stages
INFO [runner] Processors filtering stat (out/in): path_shortener: 1/1, cgo: 1/1, autogenerated_exclude: 1/1, max_same_issues: 1/1, max_from_linter: 1/1, fixer: 1/1, filename_unadjuster: 1/1, path_prettifier: 1/1, nolint: 1/1, severity-rules: 1/1, source_code: 1/1, path_prefixer: 1/1, sort_results: 1/1, skip_files: 1/1, identifier_marker: 1/1, diff: 1/1, max_per_file_from_linter: 1/1, skip_dirs: 1/1, exclude: 1/1, exclude-rules: 1/1, uniq_by_line: 1/1
INFO [runner] processing took 1.174717ms with stages: nolint: 861.696µs, skip_files: 79.721µs, source_code: 68.915µs, identifier_marker: 55.991µs, autogenerated_exclude: 55.156µs, path_prettifier: 26.107µs, skip_dirs: 13.384µs, max_same_issues: 2.289µs, max_per_file_from_linter: 1.76µs, uniq_by_line: 1.714µs, cgo: 1.608µs, path_shortener: 1.421µs, max_from_linter: 1.188µs, severity-rules: 1.051µs, filename_unadjuster: 718ns, exclude-rules: 482ns, path_prefixer: 362ns, exclude: 331ns, fixer: 317ns, diff: 276ns, sort_results: 230ns
INFO [runner] linters took 212.174742ms with stages: goanalysis_metalinter: 210.882877ms
stats/stats.go:86:14: fieldalignment: struct with 552 pointer bytes could be 536 (govet)
type UeStats struct {
             ^
INFO File cache stats: 1 entries of total size 10.4KiB
INFO Memory: 13 samples, avg is 36.5MB, max is 77.5MB
INFO Execution took 1.163618705s
```

**Comment by patriciareinoso** [comment]
> @patriciareinoso, any suggestion on how to fix the lint issue in this PR? Thanks!
> 
> ```shell
> $ golangci-lint run -v --config ./.golangci.yml
> INFO [config_reader] Used config file .golangci.yml
> INFO [lintersdb] Active 11 linters: [asciicheck dogsled goconst godox gofmt gofumpt govet ineffassign misspell staticcheck unused]
> INFO [loader] Go packages loading at mode 575 (types_sizes|compiled_files|exports_file|files|imports|deps|name) took 834.21036ms
> INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 15.41072ms
> INFO [linters_context/goanalysis] analyzers took 0s with no stages
> INFO [runner] Processors filtering stat (out/in): path_shortener: 1/1, cgo: 1/1, autogenerated_exclude: 1/1, max_same_issues: 1/1, max_from_linter: 1/1, fixer: 1/1, filename_unadjuster: 1/1, path_prettifier: 1/1, nolint: 1/1, severity-rules: 1/1, source_code: 1/1, path_prefixer: 1/1, sort_results: 1/1, skip_files: 1/1, identifier_marker: 1/1, diff: 1/1, max_per_file_from_linter: 1/1, skip_dirs: 1/1, exclude: 1/1, exclude-rules: 1/1, uniq_by_line: 1/1
> INFO [runner] processing took 1.174717ms with stages: nolint: 861.696µs, skip_files: 79.721µs, source_code: 68.915µs, identifier_marker: 55.991µs, autogenerated_exclude: 55.156µs, path_prettifier: 26.107µs, skip_dirs: 13.384µs, max_same_issues: 2.289µs, max_per_file_from_linter: 1.76µs, uniq_by_line: 1.714µs, cgo: 1.608µs, path_shortener: 1.421µs, max_from_linter: 1.188µs, severity-rules: 1.051µs, filename_unadjuster: 718ns, exclude-rules: 482ns, path_prefixer: 362ns, exclude: 331ns, fixer: 317ns, diff: 276ns, sort_results: 230ns
> INFO [runner] linters took 212.174742ms with stages: goanalysis_metalinter: 210.882877ms
> stats/stats.go:86:14: fieldalignment: struct with 552 pointer bytes could be 536 (govet)
> type UeStats struct {
>             ^
> INFO File cache stats: 1 entries of total size 10.4KiB
> INFO Memory: 13 samples, avg is 36.5MB, max is 77.5MB
> INFO Execution took 1.163618705s
> ```

type UeStats struct {
	CSvc    ServiceReq
	CPdu    PduSessEst
	CCtxrel CtxRelease
	CDreg   Deregistration
	Reg     []Registration // Historical. After completion move CReg here
	Pdu     []PduSessEst
	Svc     []ServiceReq
	Ctxrel  []CtxRelease
	Dreg    []Deregistration
	Supi    string
	CReg    Registration // Current
}

or 

type UeStats struct {
	Reg     []Registration // Historical. After completion move CReg here
	Pdu     []PduSessEst
	Svc     []ServiceReq
	Ctxrel  []CtxRelease
	Dreg    []Deregistration
	CSvc    ServiceReq
	CPdu    PduSessEst
	CCtxrel CtxRelease
	CDreg   Deregistration
	Supi    string
	CReg    Registration // Current
}
should fix the problem

**Comment by gab-arrobo** [comment]
@patriciareinoso, thanks for the suggestion

**Comment by gab-arrobo** [comment]
I just finished to run a test and I got the following error:

```
2024-02-10T00:52:44Z [TRAC][GNBSIM][RealUe][imsi-208930100007501] Sending SERVICE-ACCEPT-EVENT to SimUe
2024-02-10T00:52:44Z [INFO][GNBSIM][SimUe][imsi-208930100007501] Handling event: SERVICE-ACCEPT-EVENT
2024/02/10 00:52:44 *******Received Event : SVC_ACCEPT_IN:  &{0001-01-01 00:00:00 +0000 UTC imsi-208930100007501 35 235}
2024/02/10 00:52:44 No transaction found for Id: 235
2024-02-10T00:52:44Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Wrote 24 bytes
2024-02-10T00:52:44Z [INFO][GNBSIM][GNodeB][ControlPlaneTransport] Message Id ****************  0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xafa9c5]

goroutine 4 [running]:
github.com/omec-project/gnbsim/stats.readStats()
        /go/src/gnbsim/stats/stats.go:270 +0x1a45
created by github.com/omec-project/gnbsim/stats.init.0 in goroutine 1
        /go/src/gnbsim/stats/stats.go:118 +0x54
command terminated with exit code 2
```

**Review by gab-arrobo — APPROVED** [review]
+1 (LGTM and also tested PR with OnRamp)

**Pull request merged**
